### ISSUE TITLE
resestEaddress() function

### ISSUE THREAD

**Issue by MrHIB** [FhenixProtocol/fhenix-contracts#48]
What happened to the resestEaddress() function to reencrypt an eaddress?
can't find it in the fhenix-contracts repo

**Comment by Cashmaney** [comment]
`eaddress` was moved to a native type, so the old contract was removed. Depending on what you want to achieve, you can do the same thing by just calling select (if I understand correctly what you're trying to do)

```solidity
        eaddress a = FHE.select(FHE.asEbool(true), FHE.asEaddress("0xb794f5ea0ba39494ce839613fffba74279579268"), FHE.asEaddress(0));
```
